### ISSUE TITLE
Bug: Archive wrong itemID when more simplelists

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-for-Joomla-4#1]
I migrate this to this place: (the old issues of Heklaterriol are missing)

In a site there are two simplelists: the first 'A' shows categories 'C' and 'D', the second shows categories 'E' and 'F'.
By clicking on archive (and viewing the url), there is always the archive of only simplelist 'A' (with itemID of 'A')

**Comment by mckillo** [comment]
Solved. Check it. See the commit 3d6c2e79cbd8d84c1d0e3167a10f779e82446212.

**Comment by jojo12** [comment]
can be closed
