### ISSUE TITLE
consolidate icon font load (fontawsome)

### ISSUE THREAD

**Issue by Heklaterriol** [jemproject/JEM-for-Joomla-4#12]
JEM has now fontawesome 5 included. 
But I think we could possibly reduce the page load by using the Joomla native icon font instance.

**Comment by mckillo** [comment]
![JEM4_FontAwesome_5 15 4_vs_JL43_FontAwesome_4 7](https://user-images.githubusercontent.com/2765316/235612512-d07bd2c6-cdb6-4bef-9319-8835de2191a3.jpg)

The versions are diferents. JEM4 use last FontAwesome_5.15.4_and Joomla 4.3 use old FontAwesome 4.7

**Comment by jojo12** [comment]
what does this mean?

**Comment by mckillo** [comment]
Hekla proposed to use the fontaawesome of J4 and delete fontawesome 5 included into JEM, but the versions are different.
I don't know if there are many differences between versions.

**Comment by Heklaterriol** [comment]
I initially thought that Joomla uses fontawesome 4 too …
There are differences, so we can leave it as it is, or change all fontawesome instances from version 5 to 4 and remove the fontawesome 5 font from JEM … 
I guess not so important – when released and we have nothing to do anymore.

**Comment by Heklaterriol** [comment]
strange:
in media/system/css/joomla-fontawesome.css it is fa5.
also in the Admin template /media/templates/administrator/atum/css/vendor/fontawesome-free/fontawesome.min.css …

**Comment by mckillo** [comment]
@Heklaterriol Check this commit (see above), I have eliminated fontawesome. I don't see any error (front and back views) and a lot of icons are loaded directly from image files.

**Comment by Heklaterriol** [comment]
> @Heklaterriol Check this commit (see above), I have eliminated fontawesome. I don't see any error (front and back views) and a lot of icons are loaded directly from image files.

Looks good.
Only during the installation of your branch (debug_mckillo), I get a warning that FontAwesome cannot be found.
see my fix.

**Comment by mckillo** [comment]
Yes, you're right.Thank for testing it. Can be closed.

**Comment by jojo12** [comment]
I tested too, will close

**Comment by Heklaterriol** [comment]
I took it over to the main branch.
