### ISSUE TITLE
geocomplete.js update?

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-for-Joomla-4#21]
geocomplete.js works only half, better than nothing. But anyway it could be updated from 1.5 to the last 1.7
https://github.com/ubilabs/geocomplete

**Comment by mckillo** [comment]
1.5 (2012) --> 1.7 (2017) Are you testing v.1.7? Works? If it's ok, we can update one file to the package.
This last version of geocomplete is not maintained from 2017 (6 years ago).
It would be good to look for an alternative in the near future or next release

**Comment by jojo12** [comment]
I tested, it works the same way (not better than the old one).
I agree, but this is not a releseblocker.

**Comment by mckillo** [comment]
Add last version v.1.7 (see commit above)
