### ISSUE TITLE
New 'Include subcategories' attribute in Simplelist view

### ISSUE THREAD

**Issue by mckillo** [jemproject/JEM-for-Joomla-4#24]
From forum entry request this feature in Simplelist view:
https://www.joomlaeventmanager.net/forum/general-topics,-help-and-tutorials/12305-simplelist-events-from-parent-category/reply/30155

Define the list categories that you want to see in the eventlist view, but now it can set the attibute to include all subcategories tree for each parent categories define.

![JEM -add children categories of list categories (parent) for eventlist view](https://user-images.githubusercontent.com/2765316/236802109-b5908ea9-0903-4911-b6e9-b9882fac4e43.jpg)

**Comment by mckillo** [comment]
@jojo12 @Heklaterriol If you want to test it, a feedback is appreciated. I think that this feature is useful to this view.

**Comment by mckillo** [comment]
@jojo12 Solved... null error. See new commit 0db005f8ed9c3a457260eafa6de1be1f79ffe738

**Comment by jojo12** [comment]
Now, I don't get any error! Thanks
