### ISSUE TITLE
why there is in en-GB now: COM_JEM_EVENT_READ_MORE_TITLE ?

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-for-Joomla-4#26]
why there is in en-GB now: COM_JEM_EVENT_READ_MORE_TITLE ?
in mod_jem_teaser and mod_jem_banner and perhaps more
That's bad! it must be translated in the module language file (you can't think, you made it once for all, perhaps there is a possibility for a language library i don't know.
I hope, it's only the site language!

**Comment by jojo12** [comment]
Can we have a last version, please!
I don't know with which version I should test!

**Comment by mckillo** [comment]
Now, the last version of 4beta is JEM-for-Joomla-4/main, but we don't have new package

**Comment by jojo12** [comment]
I downloaded the main from JEM-for-Joomla-4 and made a package from it and installed. There is this language problem!
ful catastroph:
![lang-en](https://github.com/jemproject/JEM-for-Joomla-4/assets/2960236/203db5f9-7d82-496d-b5d3-7bde7ff01208)

**Comment by mckillo** [comment]
Hekla had commented the strings don't used  in ini files. He'll have to check again what strings are obsolete. 
Wordaround uncomment/delete ; at the begining of the line in ini languages file for those tags.
It's a little scare, it'll debug it and have an easy solution....tomorrow :-)

**Comment by mckillo** [comment]
This night or in early morning I debug it.

**Comment by jojo12** [comment]
yes, it's away, what was this?

**Comment by mckillo** [comment]
Some slashes were missing for the quotation marks. For it, broken the file and all strings don't work.

**Comment by jojo12** [comment]
can be closed
