### ISSUE TITLE
CSS Manager and custom css files

### ISSUE THREAD

**Issue by Heklaterriol** [jemproject/JEM-for-Joomla-4#7]
In the CSS manager there is also space for custom css files.

But where should they be, to appear in the CSS manager?
I tried all kind of file names and places – no success.
The code is

```
<?php if (!empty($this->files['custom'])) : ?>
  <ul>
    <?php foreach ($this->files['custom'] as $file) : ?>
      <li>
        <?php if ($canDo->get('core.edit')) : ?>
          <a href="<?php echo Route::_('index.php?option=com_jem&task=source.edit&id='.$file->id);?>">
        <?php endif; ?>
        <?php echo Text::sprintf('COM_JEM_CSSMANAGER_EDIT_CSS', $file->name);?>
        <?php if ($canDo->get('core.edit')) : ?>
          </a>
        <?php endif; ?>
      </li>
    <?php endforeach; ?>
  </ul>
<?php endif; ?>

```

**Comment by jojo12** [comment]
This was before of jem-resonsive. So if it is not disabled it only should work on legacy style. Never tried again.

**Comment by jojo12** [comment]
it is strange: I tried: in media/com_jem/css/custom I copied jem.css and renamed it to mystyle.css.
Then I set jem.css=yes and added: /media/com_jem/css/custom/mystyle.css
When I look now into the manager I see, it uses mystyle.css. When I change something in the manager, it changes.
But when I change the same in the mystyle.css, it change nothing!

**Comment by mckillo** [comment]
Check it. Before the path was site root (wrong) and I think that the right path is a subfolder custom into css path.
If you define a new custom css file in JEM Setting-Layout-Custom Stylesheets, when go to the CSS Manager, you can see in the right side this custom css, and clic to edit/save.

![JEM4-Show_the_css_custom_file_into_css_manger_to_edit](https://user-images.githubusercontent.com/2765316/235347419-f66cf79d-2527-4099-a696-af93cc494466.jpg)

**Comment by mckillo** [comment]
Fixid. See the commit above.

**Comment by jojo12** [comment]
perhaps, the help file for this should be adapted!

**Comment by mckillo** [comment]
@joj12 Tell me if now it's ok

**Comment by jojo12** [comment]
@mckillo:
I am quite sure, that the custom stylesheet part works only with the legacy style! and the other part of settings works only with the standard (responsive) style!

**Comment by mckillo** [comment]
No, JEM loads custom css file in the view.html.php of each view, so, it can be used by default and responsive styles. 
There are others generic as jem and print css files , used en several view. And one for backend (backend.css)

**Comment by jojo12** [comment]
sorry, you're right! But it is important to insert the whole URL to the JEM setting: "/media/com_jem/css/custom"
(Because the files have to be in the /css/custom folder, I thought, I can only write the name of the file! This is wrong.)

**Comment by jojo12** [comment]
my question: if the custom file have to be in css/custom and in no other place (isn't it), would it be better, you have to right down only the file name?

**Comment by jojo12** [comment]
Yes, and you're right too: the background-color, color and border settings in jem, are for both styles!!! I didn't know.

**Comment by mckillo** [comment]
The custom css file have to save in /media/com_jem/css/custom/ folder and in the Setting, only write the name css files (without any path).

**Comment by jojo12** [comment]
doesn't work.
How I test:
I  have a renamed copy from jem.css (jem-responsive.css) in the folder /media/com_jem/css/custom. They're named my-jem.css (my-jem-responsive.css)
In the JEM settings I write in the input field of jem.css -> my-jem.css (my-responsive-jem.css.
I go to menue simplelist with firefox developer,click the right mousebutton and look into the inspector:
There is no use of my-jem.css (my.responsive-jem.css)
(When it would work, I should see use of these files!)

Only when I write the whole "/media/com_jem/css/custom", I see the use of these files!

**Comment by mckillo** [comment]
I agree with you, I changed the path for CSS Manager in the code (back), but I don't change the path for the view (front), sorry.
Thanks for testing. You can test the new commit above.

**Comment by Heklaterriol** [comment]
Thanks for taking care of the issue.
I can see the file (e.g. customstyle.css), but when I click on "Edit customstyle.css" I get an error message "Source file not found Source file not found" (yes twice the text)

**Comment by mckillo** [comment]
Can be that this file is empty (sizefile OKB). Review the code for the doble message.

**Comment by jojo12** [comment]
I don't get a double message!

But what should  the following do? and what does it?

"Press F10 to toggle Full Screen editing."

**Comment by mckillo** [comment]
I guess that you creaste a new file into css custom folder, but this file is empty.
For the double message, I'll try to simulate and review the code.

**Comment by Heklaterriol** [comment]
> "Press F10 to toggle Full Screen editing."

In my case it does not work – I suggest that we delete this hint.

**Comment by mckillo** [comment]
@Heklaterriol Check it. Now you can edit it when this css fiel is empty (new). See the commit above.

**Comment by Heklaterriol** [comment]
Cool.
It works and I added instructions how to list the custom stylesheets.

**Comment by Heklaterriol** [comment]
I think we can merge it into the main branch an close it. Do you agree?

**Comment by jojo12** [comment]
I agree
