### ISSUE TITLE
Many PHP warnings in /components/com_jem/models/event.php

### ISSUE THREAD

**Issue by over40** [jemproject/JEM-for-Joomla-4#8]
Hi there.. i get many PHP warnings:
PHP Warning:  Attempt to read property "attribs" on null in ....../components/com_jem/models/event.php on line 168

				# Convert parameter fields to objects.
				$registry = new JRegistry;
		   168:         $registry->loadString($data->attribs);
				$data->params = JemHelper::globalattribs(); // returns JRegistry object
				$data->params->merge($registry);

**Comment by jojo12** [comment]
please give infos about your system, or are you on a clean joomla!

**Comment by over40** [comment]
Hi jojo12,
Joomla v 4.3.0
PHP v 8.1.16
I had installed JEM 2.3.15, just upgraded to 2.3.17
Will have a further look and than comment it.
Thank you.

**Comment by jojo12** [comment]
Thanks, I can't reproduce this. Would be good to know the params you've set!

**Comment by mckillo** [comment]
@over40 If you don't any event, there isn't data (or events have empty attribs field) and we have this error. 
It is already controlled and solved with this commit (see above).

**Comment by over40** [comment]
@mckillo, since i have activated this 3 lines no more warnings were generated. Thanks for the tip.
