### ISSUE TITLE
deprecated in frontend>event detail

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-for-Joomla-4#9]
only when standard style AND icon font =no, I get:

Deprecated: strtotime(): Passing null to parameter #1 ($datetime) of type string is deprecated in /home/httpd/vhosts/pc-erlinsbach.ch/Joomla.pc-erlinsbach.ch/components/com_jem/views/event/tmpl/responsive/default.php on line 30

**Comment by mckillo** [comment]
But If you see this deprecated message, the start date and end date are null, and it's rare to have an event witout any date.

`// Add expiration date, if old events will be archived or removed
if ($jemsettings->oldevent > 0) {
  $enddate = strtotime($this->item->enddates?:$this->item->dates);
  $expDate = date("D, d M Y H:i:s", strtotime('+1 day', $enddate));
  $document->addCustomTag('<meta http-equiv="expires" content="' . $expDate . '"/>');
}`

**Comment by jojo12** [comment]
No, it is a big help planning and preparing an event, to let free the date. simplelist gives the possibility and then the events with no date are at the top!
Please if possible, give this chance!!!

**Comment by mckillo** [comment]
@jojo12 Here you are, see commit above.
If event has open date (start date and end date are null), the meta data expires at the end of day.
`$enddate = strtotime($this->item->enddates?:($this->item->dates?:date("Y-m-d")));`

**Comment by jojo12** [comment]
I tested in legacy and standard style, it works in both! thanks
